from io import BytesIO
from textwrap import shorten
from typing import Any, Dict, Iterable, List

from app.core.config import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_report(data: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "tool": settings.APP_NAME,
        "version": settings.APP_VERSION,
        **data,
    }


def build_pdf_report(data: Dict[str, Any]) -> bytes:
    report = build_report(data)
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = styles["Heading1"]
    title_style.textColor = colors.HexColor("#2563EB")
    section_style = styles["Heading3"]
    section_style.textColor = colors.HexColor("#111827")
    body_style = styles["BodyText"]
    mono_style = ParagraphStyle(
        "Mono",
        parent=body_style,
        fontName="Helvetica",
        fontSize=8,
        leading=10,
    )

    story: List = []
    story.extend(_build_header(report, title_style, body_style))
    story.extend(_build_summary_cards(report, styles))
    story.extend(_build_latency_section(report, section_style, body_style))
    story.extend(_build_bullet_section("Detected Issues", report.get("issues_detected") or [], section_style, body_style))
    story.extend(_build_bullet_section("AI Insights", report.get("ai_insights") or [], section_style, body_style))
    story.extend(_build_results_table(report.get("results") or [], section_style, mono_style))

    doc.build(story)
    return buffer.getvalue()


def _build_header(report: Dict[str, Any], title_style, body_style) -> List:
    severity = str(report.get("severity") or "LOW").upper()
    score = report.get("quality_score", "N/A")
    endpoint = report.get("source", {})
    source_text = "Scheduled run" if endpoint and endpoint.get("type") == "schedule" else "Manual run"

    return [
        Paragraph("API Sentinel", title_style),
        Spacer(1, 4),
        Paragraph(f"Quality Report - Score {score} - Severity {severity}", body_style),
        Paragraph(f"Generated by {settings.APP_NAME} v{settings.APP_VERSION}", body_style),
        Paragraph(f"Run type: {source_text}", body_style),
        Spacer(1, 10),
    ]


def _build_summary_cards(report: Dict[str, Any], styles) -> List:
    summary = report.get("summary") or {}
    total_tests = report.get("total_tests", 0)
    passed = summary.get("passed", max(total_tests - summary.get("failed", 0), 0))
    failed = summary.get("failed", 0)
    severity = str(report.get("severity") or "LOW").upper()
    score = report.get("quality_score", "N/A")

    data = [
        ["Quality Score", "Severity", "Passed", "Failed"],
        [str(score), severity, str(passed), str(failed)],
    ]
    table = Table(data, colWidths=[40 * mm, 40 * mm, 40 * mm, 40 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#111827")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#CBD5E1")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("BACKGROUND", (0, 1), (-1, 1), colors.white),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [table, Spacer(1, 12)]


def _build_latency_section(report: Dict[str, Any], section_style, body_style) -> List:
    stats = report.get("latency_stats") or {}
    elements = [Paragraph("Latency Percentiles", section_style)]
    if not stats:
        elements.extend([Paragraph("No latency history available for this report.", body_style), Spacer(1, 8)])
        return elements

    sample_size = stats.get("sample_size", 0)
    data = [
        ["Sample", "P50", "P95", "P99"],
        [
            str(sample_size),
            _format_ms(stats.get("p50")),
            _format_ms(stats.get("p95")),
            _format_ms(stats.get("p99")),
        ],
    ]
    table = Table(data, colWidths=[30 * mm, 40 * mm, 40 * mm, 40 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#DBEAFE")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#93C5FD")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#BFDBFE")),
    ]))
    elements.extend([table, Spacer(1, 12)])
    return elements


def _build_bullet_section(title: str, items: Iterable[str], section_style, body_style) -> List:
    elements = [Paragraph(title, section_style)]
    items = list(items)
    if not items:
        elements.extend([Paragraph("None", body_style), Spacer(1, 8)])
        return elements

    for item in items:
        elements.append(Paragraph(f"- {item}", body_style))
    elements.append(Spacer(1, 10))
    return elements


def _build_results_table(results: List[Dict[str, Any]], section_style, body_style) -> List:
    elements = [Paragraph("Test Results", section_style)]
    if not results:
        elements.extend([Paragraph("No result rows available.", body_style), Spacer(1, 8)])
        return elements

    data = [["#", "Test", "Status", "Time", "Body Preview", "Error"]]
    for index, result in enumerate(results, start=1):
        data.append([
            str(index),
            str(result.get("test_name") or "-"),
            str(result.get("status_code") or "-"),
            _format_ms((result.get("response_time") or 0) * 1000) if result.get("response_time") is not None else "-",
            shorten(str(result.get("response_body") or "-"), width=42, placeholder="..."),
            shorten(str(result.get("error") or "-"), width=32, placeholder="..."),
        ])

    table = Table(data, repeatRows=1, colWidths=[10 * mm, 28 * mm, 18 * mm, 18 * mm, 70 * mm, 28 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("LEADING", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D1D5DB")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    elements.extend([table, Spacer(1, 8)])
    return elements


def _format_ms(value: Any) -> str:
    if value is None:
        return "-"
    try:
        return f"{round(float(value))} ms"
    except (TypeError, ValueError):
        return "-"
